"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_purple)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_purple bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#F8F7F1'
color_fg = '#232221'

color_bg1      = '#3c3836'
color_bg3      = '#665c54'
color_blue     = '#8DACE2'
color_aqua     = '#ABEDE4'
color_green    = '#A1CC85'
color_orange   = '#E68A5C'
color_purple   = '#DCB8E6'
color_red      = '#E67373'
color_yellow   = '#EDD282'

[os]
disabled = false
style = "bg:color_orange fg:color_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg"
style_root = "bg:color_orange fg:color_fg"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[c]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[rust]
symbol = "󱘗"
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[golang]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[php]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[java]
symbol = " "
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[kotlin]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[haskell]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[python]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_purple)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_blue)'
vimcmd_replace_symbol = '[](bold fg:color_blue)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
