[manager]
cwd = { fg = "#7accc1" }

# Hovered
hovered = { fg = "#1c1c19", bg = "#8dace2" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#dcb8e6", italic = true }
find_position = { fg = "#ed9797", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#8dace2", bg = "#8dace2" }
marker_copied = { fg = "#a1cc85", bg = "#a1cc85" }
marker_cut = { fg = "#e67373", bg = "#e67373" }

# Tab
tab_active   = { fg = "#1c1c19", bg = "#e0def4" }
tab_inactive = { fg = "#e0def4", bg = "#525367" }
tab_width    = 1

# Count
count_copied   = { fg = "#1c1c19", bg = "#a1cc85" }
count_cut      = { fg = "#1c1c19", bg = "#e67373" }
count_selected = { fg = "#1c1c19", bg = "#8dace2" }

# Border
border_symbol = "│"
border_style = { fg = "#282a2e" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#383b41", bg = "#383b41" }

# Mode
mode_normal = { fg = "#1f1f1e", bg = "#abede4", bold = true }
mode_select = { fg = "#1f1f1e", bg = "#a1cc85", bold = true }
mode_unset = { fg = "#e0def4", bg = "#e67373", bold = true }

# Progress
progress_label = { fg = "#e0def4", bold = true }
progress_normal = { fg = "#191724", bg = "#383b41" }
progress_error = { fg = "#e67373", bg = "#383b41" }

# Permissios 
# permissions_t = { fg = "#31748f" } # Interesting color, keep for reference
permissions_t = { fg = "#8dace2" }
permissions_r = { fg = "#edd282" }
permissions_w = { fg = "#ed9797" }
permissions_x = { fg = "#abede4" }
permissions_s = { fg = "#525367" }

# : }}}
  
# : Input {{ 

[input]
border = { fg = "#525367" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#525367" }
active = { fg = "#ed9797" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#525367" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#302F2C" }
cand = { fg = "#7accc1" }
rest = { fg = "#383b41" }
desc = { fg = "#ed9797" }
separator = "  "
separator_style = { fg = "#889b90" }

# : }}}


# : Help {{{

[help]
on = { fg = "#ed9797" }
exec = { fg = "#7accc1" }
desc = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer = { fg = "#302F2C", bg = "#e0def4" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#dcb8e6" },  
    # Videos
    { mime = "video/*", fg = "#abede4" },
    { mime = "audio/*", fg = "#abede4" },

    # Archives
    { mime = "application/zip", fg = "#ed9797" },
    { mime = "application/gzip", fg = "#ed9797" },
    { mime = "application/x-tar", fg = "#ed9797" },
    { mime = "application/x-bzip", fg = "#ed9797" },
    { mime = "application/x-bzip2", fg = "#ed9797" },
    { mime = "application/x-7z-compressed", fg = "#ed9797" },
    { mime = "application/x-rar", fg = "#ed9797" },

    # Fallback
    { name = "*", fg = "#e6dfca" },
    { name = "*/", fg = "#7A96C2" },
]

# : }}}
